apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    ports:
    - name: nexus
      port: 8081
    selector:
      name: nexus
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: nexus
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: nexus
      spec:
        containers:
        - env: []
          image: nexus
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            tcpSocket:
              port: 8081
            timeoutSeconds: 1
          name: nexus
          ports:
          - containerPort: 8081
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - curl 127.0.0.1:8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - mountPath: /opt/nexus/sonatype-work
            name: nexus-data
        volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus
    triggers:
    - type: ConfigChange
kind: List
metadata: {}
