FROM rhscl/mysql-57-rhel7

# MySQL image for DO180
#
# Volumes:
#  * /var/lib/mysql/data - Datastore for MySQL
#    /var/lib/mysql/init - Folder to load *.sql scripts
# Environment:
#  * $MYSQL_USER - Database user name
#  * $MYSQL_PASSWORD - User's password
#  * $MYSQL_DATABASE - Name of the database to create
#  * $MYSQL_ROOT_PASSWORD (Optional) - Password for the 'root' MySQL account

ADD root /
